### ISSUE TITLE
Port to a Modern Language?

### ISSUE THREAD

**Issue by xperia64** [Gamer2020/Unofficial-A-ptch#1]
I thank you for uploading the source, which otherwise was lost. I know HackMew wrote this, but do you happen to have any idea how it works?
I'm trying to do a Java port, and am having issues with a lot of things. After sorting out that an integer is 16 bits and a long is 32 bits in VisualBasic 5, I attempted to rewrite everything. The RtlMoveMemory stuff and the entire CRC process is difficult to understand.
I am aware there are superior patch formats, but my users want this one for some reason.

**Comment by xperia64** [comment]
I managed to rewrite the ApplyPatch stuff in Java, and it appears to work fine: https://github.com/xperia64/android-rom-patcher/blob/master/src/com/xperia64/rompatcher/javapatchers/APSGBAPatcher.java

**Comment by Gamer2020** [comment]
I apologize for not being able to reply sooner. I have been very busy latley. I am glad you were able to get it to work. Good luck!

Please make sure to credit HackMew as APS was his creation. Thank you!
